// schema generated by http://jsonschema.net/
const schema = {
  "type": "object",
  "properties": {
    "concept": {
      "type": "string"
    },
    "type": {
      "type": "string", enum: ['dimension', 'subdim']
    },
    "subdim_of": {
      "type": "string"
    },
    "name": {
      "type": "string"
    },
    "name_short": {
      "type": "string"
    },
    "name_long": {
      "type": "string"
    },
    "link": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "usability": {
      "type": "string"
    },
    "total_entity": {
      "type": "string"
    },
    "total_name": {
      "type": "string"
    },
    "default_entities": {
      "type": "string"
    },
    "drilldowns": {
      "type": "string"
    },
    "drillups": {
      "type": "string"
    },
    "incomplete_drillups": {
      "type": "string"
    },
    "ordinal": {
      "type": "string"
    },
    "measure": {
      "type": "string"
    },
    "interval": {
      "type": "string"
    },
    "cardinality": {
      "type": "string"
    },
    "aliases": {
      "type": "string"
    },
    "pattern": {
      "type": "string"
    },
    "ddf_inheritance": {
      "type": "string"
    }
  },
  "required": [
    "concept",
    "type",
    "subdim_of",
    "name",
    "name_short",
    "name_long",
    "link",
    "description",
    "usability",
    "total_entity",
    "total_name",
    "default_entities",
    "drilldowns",
    "drillups",
    "incomplete_drillups",
    "ordinal",
    "measure",
    "interval",
    "cardinality",
    "aliases",
    "pattern",
    "ddf_inheritance"
  ]
};

module.exports = {
  fileName: 'ddf--dimensions.csv',
  fileExp: /^ddf--dimensions\.csv$/i,
  gid: 'concept',
  schema: schema
};
