// schema generated by http://jsonschema.net/
const schema = {
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "/",
  "type": "object",
  "properties": {
    "measure": {
      "id": "measure",
      "type": "string"
    },
    "name": {
      "id": "name",
      "type": "string"
    },
    "name_short": {
      "id": "name_short",
      "type": "string"
    },
    "description": {
      "id": "description",
      "type": "string"
    },
    "definition_snippet": {
      "id": "definition_snippet",
      "type": "string"
    },
    "title": {
      "id": "title",
      "type": "string"
    },
    "low_label_short": {
      "id": "low_label_short",
      "type": "string"
    },
    "low_label": {
      "id": "low_label",
      "type": "string"
    },
    "high_label_short": {
      "id": "high_label_short",
      "type": "string"
    },
    "high_label": {
      "id": "high_label",
      "type": "string"
    },
    "good_direction": {
      "id": "good_direction",
      "type": "string"
    },
    "tags": {
      "id": "tags",
      "type": "string"
    },
    "link": {
      "id": "link",
      "type": "string"
    },
    "usability": {
      "id": "usability",
      "type": "string"
    },
    "unit": {
      "id": "unit",
      "type": "string"
    },
    "value_interval": {
      "id": "value_interval",
      "type": "string"
    },
    "scales": {
      "id": "scales",
      "type": "string"
    },
    "precision_maximum": {
      "id": "precision_maximum",
      "type": "string"
    },
    "decimals_maximum": {
      "id": "decimals_maximum",
      "type": "string"
    },
    "ddf_origin": {
      "id": "ddf_origin",
      "type": "string"
    }
  },
  "required": [
    "measure",
    "name",
    "name_short",
    "description",
    "definition_snippet",
    "title",
    "low_label_short",
    "low_label",
    "high_label_short",
    "high_label",
    "good_direction",
    "tags",
    "link",
    "usability",
    "unit",
    "value_interval",
    "scales",
    "precision_maximum",
    "decimals_maximum",
    "ddf_origin"
  ]
};

module.exports = {
  fileName: 'ddf--measures.csv',
  fileExp: /^ddf--measures\.csv$/i,
  gid: 'measure',
  schema: schema
};
